// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tt.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	tt.proto

It has these top-level messages:
	ReqTT
	TTPack
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqTT struct {
	ClientID int32 `protobuf:"varint,1,opt,name=ClientID" json:"ClientID,omitempty"`
}

func (m *ReqTT) Reset()                    { *m = ReqTT{} }
func (m *ReqTT) String() string            { return proto.CompactTextString(m) }
func (*ReqTT) ProtoMessage()               {}
func (*ReqTT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqTT) GetClientID() int32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

type TTPack struct {
	Index     int32 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	TimeStamp int64 `protobuf:"varint,2,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *TTPack) Reset()                    { *m = TTPack{} }
func (m *TTPack) String() string            { return proto.CompactTextString(m) }
func (*TTPack) ProtoMessage()               {}
func (*TTPack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TTPack) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TTPack) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqTT)(nil), "msg.ReqTT")
	proto.RegisterType((*TTPack)(nil), "msg.TTPack")
}

func init() { proto.RegisterFile("tt.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x29, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe6, 0x62, 0x0d, 0x4a, 0x2d,
	0x0c, 0x09, 0x11, 0x92, 0xe2, 0xe2, 0x70, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xf1, 0x74, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x95, 0x6c, 0xb8, 0xd8, 0x42, 0x42, 0x02, 0x12, 0x93,
	0xb3, 0x85, 0x44, 0xb8, 0x58, 0x3d, 0xf3, 0x52, 0x52, 0x2b, 0xa0, 0x4a, 0x20, 0x1c, 0x21, 0x19,
	0x2e, 0xce, 0x90, 0xcc, 0xdc, 0xd4, 0xe0, 0x92, 0xc4, 0xdc, 0x02, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0xe6, 0x20, 0x84, 0x40, 0x12, 0x1b, 0xd8, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0x03, 0x3c, 0xd3, 0x7a, 0x00, 0x00, 0x00,
}
